### ISSUE TITLE
Dump Request/Response On HTTP Response Code >= 300

### ISSUE THREAD

**Issue by wonderstim** [Adyen/adyen-go-api-library#324]
**Is your feature request related to a problem? Please describe.**
In dev I just always have debug on. I can't do that in production obviously, but because the API is generated it is actually pretty annoying to dump requests bodies from failed requests. This is particularly annoying when I am seeing 422 errors where the invalid parameters array is also empty.

**Describe the solution you'd like**
Similar to the debug configuration, just an option for dumping reqeusts and responses is the HTTP status code is not 2XX

**Describe alternatives you've considered**
Manually json marshaling each and every input on a returned error. This is a LOT of copy/pasted code.

**Additional context**

**Comment by gcatanese** [comment]
@wonderstim Hey Tim, I have created a PR to address the shortcoming, please let me know what you think.

Our long-term solution is to unify the error handling of all APIs so that we will be able to expose consistently any error using the same object (model) with all the necessary info (i.e. `InvalidFields`)

**Comment by wonderstim** [comment]
Ok I will try it out in the new year. We are in code freeze for the holidays atm. Thanks.
